CREATE TABLE roles (
         id INT PRIMARY KEY,
         role_name VARCHAR(20) NOT NULL,

         CONSTRAINT chk_id_values CHECK (id IN (1, 2)),
         CONSTRAINT chk_role_type_values CHECK (role_name IN ('applicant', 'employer'))
);

INSERT INTO roles (id, role_name) VALUES (1, 'applicant');
INSERT INTO roles (id, role_name) VALUES (2, 'employer');


CREATE TABLE categories (
     id INT PRIMARY KEY,
     name VARCHAR(100) NOT NULL UNIQUE,
     parent_id INT,

     CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES categories(id),
     CONSTRAINT chk_category_name CHECK (name IN ('Юрист', 'Экономист', 'Айти специалист', 'Монтажник'))
);

INSERT INTO categories (id, name, parent_id) VALUES (1, 'Юрист', NULL);
INSERT INTO categories (id, name, parent_id) VALUES (2, 'Экономист', NULL);
INSERT INTO categories (id, name, parent_id) VALUES (3, 'Айти специалист', NULL);
INSERT INTO categories (id, name, parent_id) VALUES (4, 'Монтажник', NULL);


CREATE TABLE contact_types (
                               id INT PRIMARY KEY,
                               type VARCHAR(50) NOT NULL UNIQUE,

            CONSTRAINT chk_contact_type CHECK (type IN (
                    'Telegram', 'Mail', 'Facebook', 'Whatsapp', 'Linkedin'))
);

INSERT INTO contact_types (id, type) VALUES
          (1, 'Telegram'),
          (2, 'Mail'),
          (3, 'Facebook'),
          (4, 'Whatsapp'),
          (5, 'Linkedin');


CREATE TABLE users (
          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR(100) NOT NULL,
          surname VARCHAR(100),
          age INT,
          email VARCHAR(150) NOT NULL UNIQUE,
          password TEXT NOT NULL,
          phone_number VARCHAR(55),
          avatar TEXT,
          role_id INT NOT NULL,
          CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE vacancies (
           id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
           name VARCHAR(255) NOT NULL,
           description TEXT NOT NULL,
           salary REAL,
           exp_from INT,
           exp_to INT,
           is_active BOOLEAN DEFAULT TRUE NOT NULL,
           created_date TIMESTAMP NOT NULL,
           update_time TIMESTAMP,
           category_id INT NOT NULL,
           user_id INT NOT NULL,
            CONSTRAINT fk_vacancy_category FOREIGN KEY (category_id) REFERENCES categories(id),
            CONSTRAINT fk_vacancy_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE resumes (
           id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
           name VARCHAR(45) NOT NULL,
           salary REAL,
           is_active BOOLEAN NOT NULL,
           created_date TIMESTAMP NOT NULL,
           update_time TIMESTAMP,
           user_id INT NOT NULL,
           category_id INT NOT NULL,
           CONSTRAINT fk_resume_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
           CONSTRAINT fk_resume_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE contacts_info (
          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          value TEXT NOT NULL,
          type_id INT NOT NULL,
          resume_id INT NOT NULL,
          CONSTRAINT fk_contact_info_type FOREIGN KEY (type_id) REFERENCES contact_types(id),
          CONSTRAINT fk_contact_info_resume FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE
);

INSERT INTO users (name, surname, age, email, password, phone_number, avatar, role_id) VALUES
 ('Иван', 'Иванов', 35, 'ivanov@mail.ru', '123456', '+996555030303', 'avatar_ivan.png', 1),
 ('Петр', 'Петров', 25, 'petrov@mail.ru', '123456', '+996500030303', 'avatar_petr.png', 2);

INSERT INTO resumes (user_id, name, category_id, salary, is_active, created_date, update_time) VALUES
    (
        1,
        'Айти специалист',
        3,
        20000.0,
        TRUE,
        CAST('2026-07-17 10:00:00' AS TIMESTAMP),
        NULL
    );

INSERT INTO contacts_info (type_id, resume_id, value) VALUES
               (1, 1, '@ivanbek'),
               (2, 1, 'ivanov@mail.ru');

INSERT INTO vacancies (name, description, salary, exp_from, exp_to, is_active, created_date, update_time, category_id, user_id) VALUES
    (
        'Айти специалист',
        'Требуется разраб',
        50000.0,
        1,
        3,
        TRUE,
        CAST('2026-07-17 11:00:00' AS TIMESTAMP),
        NULL,
        3,
        2
    );

INSERT INTO resumes (user_id, name, category_id, salary, is_active, created_date, update_time) VALUES
    (
        1,
        'Юрист',
        1,
        25000.0,
        TRUE,
        CAST('2026-07-17 12:00:00' AS TIMESTAMP),
        NULL
    );

INSERT INTO resumes (user_id, name, category_id, salary, is_active, created_date, update_time) VALUES
    (
        1,
        'Юрист',
        1,
        80000.0,
        TRUE,
        CAST('2026-07-17 12:00:00' AS TIMESTAMP),
        NULL
    );

INSERT INTO contacts_info (type_id, resume_id, value) VALUES
 (4, 2, '+79991112233'),
 (2, 2, 'ivanov.legal@mail.ru');

INSERT INTO vacancies (name, description, salary, exp_from, exp_to, is_active, created_date, update_time, category_id, user_id) VALUES
    (
        'Юрист',
        'Требуется юрист',
        20000.0,
        1,
        3,
        TRUE,
        CAST('2026-07-17 12:30:00' AS TIMESTAMP),
        NULL,
        1,
        2
    );

CREATE TABLE education_info (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        institution TEXT,
        program TEXT,
        start_date DATE,
        end_date DATE,
        degree TEXT,
        resume_id INT NOT NULL,
        CONSTRAINT fk_education_resume FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE
);

INSERT INTO education_info (resume_id, institution, program, start_date, end_date, degree) VALUES
    (
        1,
        'KNU',
        'IT',
        CAST('2009-09-01' AS DATE),
        CAST('2014-06-30' AS DATE),
        'Specialist'
    );

INSERT INTO education_info (resume_id, institution, program, start_date, end_date, degree) VALUES
    (
        2,
        'KRSU',
        'Law',
        CAST('2015-09-01' AS DATE),
        CAST('2017-06-30' AS DATE),
        'Bachelor'
    );

CREATE TABLE work_experience_info (
       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       years INT,
       company_name VARCHAR(100) NOT NULL,
       position VARCHAR(100) NOT NULL,
       responsibilities TEXT,
       resume_id INT NOT NULL,
       CONSTRAINT fk_experience_resume FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE
);

INSERT INTO work_experience_info (resume_id, years, company_name, position, responsibilities) VALUES
    (
        1,
        4,
        'Mega',
        'Java Developer',
        'Developing apps'
    );

INSERT INTO work_experience_info (resume_id, years, company_name, position, responsibilities) VALUES
    (
        2,
        3,
        'Beeline',
        'Lawyer',
        'Creating and analysis contracts'
    );

CREATE TABLE responded_applicants (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        confirmation BOOLEAN,
        resume_id INT NOT NULL,
        vacancy_id INT NOT NULL,
        CONSTRAINT fk_respond_resume FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE,
        CONSTRAINT fk_respond_vacancy FOREIGN KEY (vacancy_id) REFERENCES vacancies(id) ON DELETE CASCADE,
);

INSERT INTO responded_applicants (resume_id, vacancy_id, confirmation) VALUES
  (1, 1, TRUE),
  (2, 2, TRUE);